site_name: '' # Removed the site name text as requested
site_url: https://jockeys.github.io/household-guidelines/ # Your actual GitHub Pages URL
site_description: Comprehensive guidelines for a harmonious blended family.

# Crucial: Build the MkDocs site into a 'report' subdirectory
site_dir: report

nav:
  - Report: index.md # This will be the main page of your MkDocs site, living in /report/
  - Frameworks: frameworks.md # <-- Add this line
  - Analysis: toolkit_analysis.md

theme:
  name: material
  palette:
    # Define the default light palette
    - scheme: default
      primary: 'deep orange' # A warm, inviting primary color for light mode
      accent: 'light blue'   # A complementary accent color for light mode
      toggle:
        icon: material/brightness-7 # Icon for light mode (sun)
        name: Switch to dark mode
    # Define the dark palette
    - scheme: slate
      primary: 'deep orange' # Primary color for dark mode
      accent: 'light blue'   # Accent color for dark mode
      toggle:
        icon: material/brightness-4 # Icon for dark mode (moon)
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.tabs.link
    - navigation.instant # Added for smoother page transitions
    # No specific feature needed for settings icon, it's part of core theme.
  icon:
    logo: material/home # Using 'material/home' as previously discussed
  # Disable breadcrumbs to remove the second "Home" link
  breadcrumbs: false
  # Add custom CSS to increase font size
  #extra_css:
  #  - css/extra.css

markdown_extensions:
  - admonition # For callouts like notes, tips, etc.
  - pymdownx.details # For expandable sections
  - pymdownx.superfences # For improved code blocks
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list # For adding attributes to markdown elements
  - md_in_html # Allows Markdown inside HTML blocks if needed

plugins:
  - search
